spring:
  application:
    name: coupon-eureka

server:
  port: 8000

eureka:
  instance:
    hostname: localhost
  client:
    # 表示是否从 Eureka Server 获取注册信息，默认是true。
    # 因为是单节点，所以不需要同步其他节点的信息。
    fetch-registry: false
    # 是否将自己注册到 Eureka Server上，因为是单节点，所以设置为false。
    register-with-eureka: false
    # 设置 Eureka Server 所在的地址，查询服务和注册服务都需要依赖这个地址。
    service-url:
      defaultZon: htto://${eureka.instance.hostname}:${server.port}/eureka/